accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'


urlpatterns = [
    # Добавить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    path("register/", views.register, name="register"),
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Main page of the learning log
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topic/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path("new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('learning_logs.urls', namespace='learning_logs')),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Topic(models.Model):
    '''Тема, которую изучает пользователь'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """Информация, изученная пользователем по теме."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

        def __str__(self):
            if len(self.text) > 50:
                return f"{self.text[:50]}..."
            else:
                return f"{self.text}"

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    else:
        form = UserCreationForm()
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.


def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

def check_topic_owner(request, topic):
    """Проверяет, является ли пользователь владельцем темы."""
    if topic.owner != request.user:
        raise Http404("You are not allowed to view this topic.")


@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')

    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)  # Проверяем, что пользователь является владельцем темы
    entries = topic.entry_set.order_by('-date_added')
    context = {"topic": topic, "entries": entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)  # задерживаем сохранение
            new_topic.owner = request.user       # устанавливаем владельца
            new_topic.save()                     # теперь сохраняем
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'topic': topic, "form": form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)

    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            if request.user != topic.owner:
                raise Http404("You are not allowed to edit this entry.")
            entry = form.save(commit=False)
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Learning Log</title>
    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                Learning Log</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                            Topics</a>
                    </li>
                </ul>
                <!-- Конец ссылок в левой части панели навигации -->
                <!-- Ссылки, связанные с аккаунтом -->
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text me-2">Hello, {{ user.username }}.
                        </span>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">
                            Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">
                            Log in</a>
                    </li>
                    {% endif %}
                </ul>
                <!-- Конец ссылок, связанных с аккаунтом -->
                {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method='post'>
                    {% csrf_token %}
                    <button name='submit' class='btn btn-outline-secondary btn-sm'>
                        Log out</button>
                </form>
                {% endif %}
            </div>
            <!-- Закрывает сворачивающиеся части панели навигации -->
        </div>
        <!-- Закрывает контейнер панели навигации -->
    </nav>
    <!-- Конец панели навигации -->
    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        </div>
        {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h1 class="mb-4">{{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}
<div class="container mt-4">
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}" class="link-primary">
            {{ topic }}
        </a>
    </p>
    <p>Edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" class="w-75">
        {% csrf_token %}
        {% bootstrap_form form layout='vertical' %}
        <button type="submit" class="btn btn-success mt-3">Save changes</button>
    </form>
</div>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block page_header %}
<div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
        <h1 class="display-3">Track your learning.</h1>
        <p class="lead">Make your own Learning Log, and keep a list of the
            topics you're learning about. Whenever you learn something new
            about a topic, make an entry summarizing what you've learned.</p>
        <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}">Register &raquo;</a>
    </div>
</div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h1 class="mb-4">{{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}
<div class="container mt-4">
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}" class="link-primary">
            {{ topic }}
        </a>
    </p>
    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="w-75">
        {% csrf_token %}
        {% bootstrap_form form layout='vertical' %}
        <button type="submit" class="btn btn-primary mt-3">Add entry</button>
    </form>
</div>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
  {% block page_header %}
  <h1>{{ topic.text }}</h1>
  {% endblock page_header %}
  <form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Topic</button>
  </form>
  <a href="{% url 'learning_logs:topics' %}">Back to Topics</a>
{% endblock %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
<h1>{{ topic.text }}</h1>
{% endblock page_header %}
{% block content %}
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
</p>
{% for entry in entries %}
<div class="card mb-3">
    <!-- Заголовок панели с временной меткой и ссылкой для редактирования -->
    <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
                edit entry</a></small>
    </h4>
    <!-- Тело панели с текстом ввода -->
    <div class="card-body">{{ entry.text|linebreaks }}</div>
</div>
{% empty %}
<p>There are no entries for this topic yet.</p>
{% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
<h1>Topics</h1>
{% endblock page_header %}
{% block content %}
<ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in topics %}
    <li class="list-group-item border-0">
        <a href="{% url 'learning_logs:topic' topic.id %}">
            {{ topic.text }}</a>
    </li>
    {% empty %}
    <li class="list-group-item border-0">No topics have been added yet.</li>
    {% endfor %}
</ul>
<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
{% endblock content %}l